//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::process_regsitrations::Entity as ProcessRegsitrations;
pub use super::processes::Entity as Processes;
pub use super::recipes::Entity as Recipes;
pub use super::resources::Entity as Resources;
pub use super::steps::Entity as Steps;
