//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "processes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::process_regsitrations::Entity")]
    ProcessRegsitrations,
}

impl Related<super::process_regsitrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProcessRegsitrations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
