//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "process_steps")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub process_id: String,
    pub step_id: String,
    pub start_time: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::processes::Entity",
        from = "Column::ProcessId",
        to = "super::processes::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Processes,
    #[sea_orm(
        belongs_to = "super::steps::Entity",
        from = "Column::StepId",
        to = "super::steps::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Steps,
}

impl Related<super::processes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Processes.def()
    }
}

impl Related<super::steps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Steps.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
