//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod process_registrations;
pub mod process_steps;
pub mod processes;
pub mod recipes;
pub mod resources;
pub mod steps;
