apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-rust
  namespace: dev-cooking-api
  labels:
    app: backend-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-rust
  template:
    metadata:
      labels:
        app: backend-rust
    spec:
      containers:
        - name: backend-rust
          image: public.ecr.aws/v1n4z9j4/process-pj/cooking-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

