apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-rust
  namespace: dev-cooking-api
  labels:
    app: backend-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-rust
  template:
    metadata:
      labels:
        app: backend-rust
    spec:
      serviceAccountName: cooking-api-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "mysql-rds-aws-secrets"
      containers:
        - name: backend-rust
          image: public.ecr.aws/v1n4z9j4/process-pj/cooking-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
#
