apiVersion: v1
kind: Service
metadata:
  name: backend-rust
  namespace: dev-cooking-api
  labels:
    app: backend-rust
spec:
  selector:
    app: backend-rust
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

