name: Backend API (Rust) CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Build Docker image for medium size test
        run: docker build -t main:0.1.1 backend_python/
      - name: Build
        run: cargo build --verbose
        working-directory: backend_rust
      - name: Run tests
        run: cargo test --all
        working-directory: backend_rust

